//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCAL()
        {
            this.IMAGENESLOCAL = new HashSet<IMAGENESLOCAL>();
            this.TIPOCOMIDA = new HashSet<TIPOCOMIDA>();
        }
    
        public int IDLOCAL { get; set; }
        public Nullable<int> IDRESTAURANTE { get; set; }
        public string NOMBRELOCAL { get; set; }
        public string TIPOLOCAL { get; set; }
        public string TELEFONOLOCAL { get; set; }
        public string DIRECCIONLOCAL { get; set; }
        public string NOMBREREPRESENTANTE { get; set; }
        public string TELEFONOREPRESENTANTE { get; set; }
        public string TELEFONOADICIONAAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGENESLOCAL> IMAGENESLOCAL { get; set; }
        public virtual RESTAURANTE RESTAURANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPOCOMIDA> TIPOCOMIDA { get; set; }
    }
}
