//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mesaLibreDBEntities : DbContext
    {
        public mesaLibreDBEntities()
            : base("name=mesaLibreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IMAGENESLOCAL> IMAGENESLOCAL { get; set; }
        public virtual DbSet<LOCAL> LOCAL { get; set; }
        public virtual DbSet<RESTAURANTE> RESTAURANTE { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPOCOMIDA> TIPOCOMIDA { get; set; }
        public virtual DbSet<TIPORESTAURANTE> TIPORESTAURANTE { get; set; }
    }
}
