//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESTAURANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESTAURANTE()
        {
            this.LOCAL = new HashSet<LOCAL>();
        }
    
        public int IDRESTAURANTE { get; set; }
        public Nullable<int> IDTIPORESTAURANTE { get; set; }
        public string RAZONSOCIAL { get; set; }
        public string NOMBRECOMERCIAL { get; set; }
        public string RUC { get; set; }
        public string TELEFNORESTAURANTE { get; set; }
        public string DIRECCIONRESTAURANTE { get; set; }
        public string NOMBREREPRESENTANTE { get; set; }
        public string TELEFONOREPRESENTANTE { get; set; }
        public string TELEFONOADICIONAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCAL> LOCAL { get; set; }
        public virtual TIPORESTAURANTE TIPORESTAURANTE { get; set; }
    }
}
